### ISSUE TITLE
BlishHud and Mount Icons overlay on top of GW@ Upper left Menu

### ISSUE THREAD

**Issue by Mene-Menehune** [bennieboj/BlishHud-Mounts#56]
BlishHud and Mount Icons overlay on top of GW@ Upper left Menu.  This only happened after SoTo was released.

![Issue_2023-09-02 223810](https://github.com/manlaan/BlishHud-Mounts/assets/143919299/4fd4770a-dafd-40b0-b834-72a7ad378e3c)

**Comment by dlamkins** [comment]
You need to either update your modules or update Blish HUD. Many of the more common modules (e.g. Pathing, Event Table, etc.) Have a shim fix in them to solve this. Otherwise you should update to the latest version of Blish HUD via the prerelease option in the settings or by downloading it fresh from the website. 

In any case, this issue is unrelated to the mounts module.

**Comment by Mene-Menehune** [comment]
I have reinstalled the latest version of BlishHud 1.1.1 from your web site and the Mounts module says it is updated.  So what else am I supposed to do.  Mounts is the only module I have loaded so nothing else should be mucking up the icons…

Thanks,
Rick

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by dlamkins** [comment]
If after doing that it is still not aligned, it's because your UI scaling in the overlay settings do not match your in-game UI scaling. 

Setting it back to "sync with game" should likely resolve that.

**Comment by Mene-Menehune** [comment]
Where is the "Sync with Game" in BlishHud settings?

**Comment by dlamkins** [comment]
I'm referring to the DPI Scaling and Interface Size options found under the Graphics settings for Blish HUD.

https://blishhud.com/docs/user/overlay-settings#graphics-settings

Both default to "Automatic - Sync With Game"
