### ISSUE TITLE
Radomly swapped out of action camera on mouting

### ISSUE THREAD

**Issue by Void2258** [bennieboj/BlishHud-Mounts#64]
I am in action camera before mounting. As I mount, I am swapped out of action camera. Seems to be occurring randomly as far as I can tell. 

[blishhud.20240507-084609.log](https://github.com/bennieboj/BlishHud-Mounts/files/15237094/blishhud.20240507-084609.log)
[blishhud.20240507-103448.log](https://github.com/bennieboj/BlishHud-Mounts/files/15237095/blishhud.20240507-103448.log)

**Comment by bennieboj** [comment]
Hi, 

Could you please show since screenshots of in-game keybinds and module keybinds, kinda like this: https://github.com/bennieboj/BlishHud-Mounts/blob/main/README.md#keybinds

Also could you please indicate at which time it happens, then I can pinpoint that in the logs.
Or keep the log file as small as possible, 1300+ lines is not easy to analyze.

Also could you try to see if the problem still occurs with version 1.1.2 of BlishHUD?
You can download it [here](https://github.com/blish-hud/Blish-HUD-Prereleases/releases/download/1.1.2-ci.101/Blish.HUD.1.1.2-ci.101.zip) or update via Blish HUD itself if you have prereleases enabled in the settings.

**Comment by Void2258** [comment]
![image](https://github.com/bennieboj/BlishHud-Mounts/assets/6126362/ae0cbe28-c10d-4e14-a2f9-8d7a7be96049)
![image](https://github.com/bennieboj/BlishHud-Mounts/assets/6126362/42476b6a-ef4f-45aa-8cf4-a0b942847562)

**Comment by bennieboj** [comment]
I guess the ` is set to action camera in game as well? 

Did you have the chance to try version 1.1.2 of BlishHUD?

**Comment by Void2258** [comment]
Yes my action camera is on ` to prevent hitting it by mistake (1 is on the mouse so I never have my finger nearby).

**Comment by bennieboj** [comment]
Can you try this version?
https://github.com/blish-hud/bhud-modules/releases/download/manlaan.mounts_v1.4.11-beta1/Manlaan.Mounts-1.4.11-beta1.bhm

You can install it manually in this way **when BlishHUD is not running**: https://blishhud.com/docs/user/installing-modules/#manually-installing-modules

You can keep both this version and 1.4.10 in the modules folder, **just make sure that it picks v1.4.11-beta1 (see the module screen)**.

**Comment by bennieboj** [comment]
Closed due to lack of activity, should be fixed in 1.4.11
